font = "JetBrainsMono Nerd Font 11"
height = 20
command = "i3status-rs config-default"

tag_bg = "#282828"          # gruvbox-bg
tag_fg = "#ebdbb2"          # gruvbox-fg
tag_focused_bg = "#ebdbb2"  # gruvbox-fg
tag_focused_fg = "#282828"  # gruvbox-bg
tag_urgent_bg = "#cc241d"   # gruvbox-red
tag_urgent_fg = "#282828"   # gruvbox-bg
